# Site settings
title: Dean Davidson
# > # this means to ignore newlines until "baseurl:" <-- Commented out for now.
description: Dean Davidson - Portland-Based Software Engineering Extraordinaire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.deanpdx.com" # the base hostname & protocol for your site
twitter_username: PdxDavidson
github_username:  DeanPDX
logo: /images/2015/Dean1.jpg

# Build settings
markdown: kramdown
