# Site settings
title: Dean Davidson
description: > # this means to ignore newlines until "baseurl:"
  Dean Davidson - Portland-Based Software Engineering Extraordinaire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.deanpdx.com" # the base hostname & protocol for your site
twitter_username: PdxDavidson
github_username:  DeanPDX

# Build settings
markdown: kramdown
